#!/bin/bash
apt-add-repository ppa:swi-prolog/stable
apt-get update
apt-get install swi-prolog
python -m pip install --upgrade jswipl
mkdir ~/.local/share/jupyter/kernels
cd ~/.local/share/jupyter/kernels
mkdir jswipl && cd jswipl
wget https://raw.githubusercontent.com/targodan/jupyter-swi-prolog/master/kernel.json
